sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t chrisenoch/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chrisenoch/docker-react npm run test
